// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mission6Application.Models;

namespace Mission6Application.Migrations
{
    [DbContext(typeof(MovieApplicationContext))]
    partial class MovieApplicationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.22");

            modelBuilder.Entity("Mission6Application.Models.ApplicationResponse", b =>
                {
                    b.Property<int>("ApplicationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Director")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Edited")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Lent")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT")
                        .HasMaxLength(25);

                    b.Property<string>("Rating")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("ApplicationId");

                    b.ToTable("responses");

                    b.HasData(
                        new
                        {
                            ApplicationId = 1,
                            Category = "Fantasy",
                            Director = "Not sure",
                            Edited = true,
                            Lent = "Sarah Mackinley",
                            Notes = "Good Movie. A Little Old",
                            Rating = "PG",
                            Title = "Harry Potter and the Sorcerer's stone",
                            Year = 2004
                        },
                        new
                        {
                            ApplicationId = 2,
                            Category = "Thriller",
                            Director = "Again,Not sure",
                            Edited = false,
                            Lent = "",
                            Notes = "Kind of sad but good",
                            Rating = "PG-13",
                            Title = "The Prestige",
                            Year = 2008
                        },
                        new
                        {
                            ApplicationId = 3,
                            Category = "Fantasy",
                            Director = "I feel like I should know, but I don't",
                            Edited = true,
                            Lent = "I would never lend this to anybody",
                            Notes = "",
                            Rating = "PG-13",
                            Title = "Lord Of the Rings",
                            Year = 2006
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
